minari/dataset.pyi
minari/dataset.pyx
minari/utils/assert_name_spec.py
tutorials/DatasetCreation/dataset_creation.py
tutorials/LocalStorage/local_storage.py
tutorials/RemoteStorage/remote_storage.py

Add field for environment name, eg. "LunarLander-v2"

Environment name

---

tutorials/DatasetUsage/dataset_usage.py

update naming conventions

---

minari/dataset.pyi
minari/dataset.pyx

Includes warnings as ideally these fields would be given, but it's the author's choice. I've refrained from allowing other fields to be  None as these really should be filled in, though if anyone disagrees please speak up
Addresses #10

allow nonetypes of codelink, author and email

---

minari/dataset.pyi
minari/dataset.pyx
setup.py
tutorials/DatasetCreation/dataset_creation.py
tutorials/DatasetCreation/requirements.txt
tutorials/DatasetUsage/dataset_usage.py
tutorials/DatasetUsage/requirements.txt
tutorials/LocalStorage/local_storage.py
tutorials/LocalStorage/requirements.txt
tutorials/RemoteStorage/remote_storage.py
tutorials/RemoteStorage/requirements.txt

Adds https://github.com/Farama-Foundation/Gymnasium/pull/199 as a field in MinariDataset

Environment stack

---

.github/workflows/build-docs-version.yml
.github/workflows/manual-build-docs-version copy.yml
docs/conf.py

This PR adds versioning to the documentation website

Add docs versioning

---

docs/README.md

* Created a docs/README.md to link to a new [CONTRIBUTING.md](https://github.com/Farama-Foundation/Celshast/blob/main/CONTRIBUTING.md) for docs

Create docs/README.md to link to a new CONTRIBUTING.md for docs

---

docs/datasets/coming_soon.md
docs/index.md

- Add description to intro page
- Add download CLI to intro bash

Update docs webpage

---

docs/tutorials/dataset_creation/point_maze_dataset.py

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fix minor typo in tutorial

---

README.md

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Update README to match other Farama projects

---

docs/tutorials/dataset_creation/point_maze_dataset.py

Fix assignment operator bug (by replacing the equality operator) and minor typo in the tutorial

fix assignment operator bug and minor typo in the tutorial script

---

minari/__init__.py

Add b to beta version

---

docs/datasets/kitchen.md

Docs for the FrankaKitchen datasets

Update docs for FrankaKitchen datasets

---

pyproject.toml

Update dependencies to:
- `gymnasium-robotics>=1.2.1`
- `gymnasium>-0.28.1`

Update dependencies version

---

minari/utils.py
tests/test_dataset_combine.py

Fixes https://github.com/Farama-Foundation/Minari/issues/56#issue-1659118604

Fix for the combining multiple datasets

---

.github/workflows/build-docs-version.yml

Add the `docs/_scripts/gen_dataset_md.py` to the workflow as well as `SPHINX_GITHUB_CHANGELOG_TOKEN`

Fix build-docs-version.yml

---

docs/content/dataset_standards.md

Added table to display currently supported Observation and Action spaces as well a links to the Gymnasium Repo of each type

Observation and action Space Table

---

README.md

Pre-commit and code-style black badges
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Add badges to match Gymnasium

---

docs/tutorials/using_datasets/behavioral_cloning.py

Very minor but good to link to the libraries which are being used.

Add links to SB3 and rl_zoo3 in dataloading tutorial

---

docs/_scripts/gen_dataset_md.py
docs/content/minari_cli.md
docs/tutorials/using_datasets/behavioral_cloning.py

Add `Minari Version` to each dataset in the docs specifying which `minari` version they are compatible with.
Fix link for `rl-zoo` and fix Download CLI `note`

Minor fixes to docs

---

.github/workflows/build-publish.yml

fixed syntax error in build-publish.yml

fixed build-publish.yml

---

docs/content/basic_usage.md
docs/content/dataset_standards.md

- Remove Python 3.7 support from docs
- Fix doc typo in Tuple dataset naming `_index_id_` to `_index_id`

Some final doc updates

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/proposal.md

Update issue template for Minari

Update issue template

---

minari/data_collector/data_collector.py

fixes https://github.com/Farama-Foundation/Minari/issues/197

Fix mujoco rendering with DataCollector

---

.github/workflows/build-docs-version.yml
minari/data_collector/data_collector.py
minari/dataset/_storages/arrow_storage.py

Addresses https://github.com/Farama-Foundation/Minari/issues/175

Remove hard space checks in DataCollector

---

minari/serialization.py
minari/storage/hosting.py
minari/utils.py
pyproject.toml
tests/common.py
tests/conftest.py
tests/data_collector/callbacks/test_step_data_callback.py
tests/data_collector/test_data_collector.py
tests/dataset/test_minari_dataset.py
tests/dataset/test_minari_storage.py
tests/utils/test_dataset_creation.py

The CI reports 9000+ warnings
`======== 255 passed, 25 deselected, 9585 warnings in 284.66s (0:04:44) =========`

Reduce the number of warnings

---

docs/_scripts/gen_dataset_md.py
docs/conf.py
docs/content/basic_usage.md
minari/storage/hosting.py
minari/storage/remotes/__init__.py
minari/storage/remotes/cloud_storage.py
minari/storage/remotes/gcp.py

This PR adds support for other GCP remotes and improves code to easily add support for other remote types.

Add supports for other remotes

---

minari/dataset/minari_dataset.py

Fixes https://github.com/Farama-Foundation/Minari/issues/236

fix total_steps computation

---

minari/namespace.py
minari/storage/hosting.py
minari/storage/local.py
minari/storage/remotes/huggingface.py

Add prefix feature:
`minari.list_remote_datasets(prefix='D4RL')`
`minari.list_local_datasets(prefix='D4RL')` 
Not available on CLI yet

ENH: add prefix support

---

.github/workflows/build.yml
minari/cli.py
minari/namespace.py
minari/storage/hosting.py
minari/storage/remotes/__init__.py
minari/storage/remotes/huggingface.py
tests/common.py
tests/dataset/test_dataset_download.py
tests/test_cli.py
tests/test_namespace.py

When groups of datasets are too large, show only aggregate statistics.
Change also the remote to HuggingFace

ENH: cli list with growing datasets

---

docs/tutorials/dataset_creation/point_maze_dataset.py

Fix: (In dataset creation tutorial) Register PointMaze_Medium-v3 and Correct env.maze Access

---

minari/dataset/minari_storage.py

We do not threat as images small spaces, e.g. 16x16

fix minigrid observation decoding

---

README.md

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

docs(readme): added a link to the workflow
