- metadata_test.py
- minari/cli.py
- minari/minari_dataset.py
- minari/storage/__init__.py
- minari/storage/hosting.py
- minari/storage/local.py
- pyproject.toml
This PR adds a progress bar to each file download when downloading a Minari dataset from the Farama server. It also adds CLI commands for Minari using [`Typer`](https://typer.tiangolo.com/).
- `list`: list of all the minari datasets with some metadata. It has other two subcommands to list remote or local datasets, `minari list remote` and `minari list local`
- `delete`: delete local Minari datasets given a list of dataset names, `minari delete door-expert-v0 door-human-v0`
- `download`: download a list of remote Minari datasets, `minari download pen-expert-v0 pen-human-v0 pen-cloned-v0`
- `upload`: upload a list of local datasets to remote Farama server, json key is required. `minari upload door-expert-v0 door-human-v0 --key-path /home/user/key_file.json`
- `combine`: combine multiple …
> CLI and progress bar for downloads

- pyproject.toml
Updating pyproject toml to track gymnasium main branch.
This fixes the issue of depending on gymnasium version found at https://github.com/pseudo-rnd-thoughts/Gymnasium.git@spec_stack
> updating pyproject toml to track gymnasium main branch

- minari/data_collector/data_collector.py
- minari/dataset/minari_dataset.py
- minari/storage/local.py
This PR adds some fixes to the data collector wrapper `DataCollectorV0`:
- Increase the `_episode_id` of the `DataCollectorV0` only after the buffers are cleared when calling `clear_buffers_to_tmp_file`. Before, if the buffers were cleared and the last episode was `terminated` or `truncated`, `_episode_id` would have increased by one and an additional empty episode was included in the dataset.
- When updating a dataset with new data (from `DataCollectorV0`) add the hdf5 group links iterating through the episode id's instead of the hdf5 file episode groups. This way we make sure that the episode groups are ordered by id
- When listing local datasets only list dataset directories that include a `data/` directory
> Fixes to DataCollectorV0

- .github/workflows/build.yml
- pyproject.toml
Fix issue #72. The current pinned `h5py` version (`3.7.0`) doesn't have Python 3.11 support, bump the version to `h5py>=3.8.0`. Also add Python 3.11 CI to Minari.
> Give Python 3.11 support

- minari/data_collector/data_collector.py
- pyproject.toml
I'm going through the repository and fixing whatever minor issues I spot. For now I'm not doing anything significant, but I'll write down potentially more complex things that need to be fixed before a full release
- data_collector.py#L102 -- self._current_seed has type `str | int`, which seems a bit sus
- data_collectory.py#L140 -- There has to be a simpler way of writing this using defaultdict or setdefault or something like that
- data_collector.py#L66-69 -- Can't the type hints be simple callables?
- The type hint for EpisodeBuffer is meant (?) to convey that it's a nested dictionary where leaves are lists. This doesn't work because `self._current_seed: int | str` is one of the possible top-level values
> General cleanup

- minari/cli.py
Previously, it showed the wrong path to datasets for `minari list local` cli command.
> fix incorrect path printing in the cli

- minari/utils.py
- tests/utils/test_dataset_combine.py
Related to https://github.com/Farama-Foundation/Minari/issues/56 
> Added option to copy data when combining datasets

- README.md
The download dataset function doesn't load the dataset; while in the current readme example it seems so.
> Fix: README download dataset

- minari/storage/hosting.py
- tests/common.py
Ruggedizes `list_remote_datasets`so it will not crash as easily if there is a misconfigured dataset in minari remote storage.
#Checklist:
> Ruggedize list_remote_datasets

- minari/storage/local.py
This PR fixes the .DS_Store issue mentioned in #97 . When accessing the local Minari datasets folder on MacOS a `.DS_Store` file gets automatically created which causes the `minari.list_local_datasets` function to fail with the following error:
```
File "/Users/username/minari/storage/local.py", line 36, in list_local_datasets
if "data" not in os.listdir(os.path.join(datasets_path, dst_id)):
NotADirectoryError: [Errno 20] Not a directory: '/Users/username/.minari/datasets/.DS_Store'
```
The implemented fix modifies the `minari.list_local_datasets` function so that it ignores hidden files when trying to list local datasets. 
Fixes #97
> ignore hidden files when listing local datasets

- docs/content/dataset_standards.md
This PR adds a section to the `Dataset Standards` documentation page describing the `EpisodeData` data structure and the fields it contains. Also includes a small snippet of sampling episodes from a Minari dataset.
> Update docs with EpisodeData info

- docs/tutorials/dataset_creation/point_maze_dataset.py
Further break down of what a PD controller was, was given, as well as explanations of the choice of equation we choose to implement.
> pd documentation

- docs/api/minari_functions.md
- minari/__init__.py
- minari/data_collector/data_collector.py
- minari/dataset/minari_dataset.py
- minari/utils.py
- tests/common.py
- tests/data_collector/test_data_collector.py
- tests/dataset/test_minari_dataset.py
- tests/utils/test_dataset_creation.py
This PR adds the [`get_normalized_score()` function from D4RL](https://github.com/Farama-Foundation/D4RL/blob/71a9549f2091accff93eeff68f1f3ab2c0e0a288/d4rl/offline_env.py#L71) for policy testing and comparisson. This function is added as a utility instead of a method in every MinariDataset since we haven't decided if we want to keep this feature for all future datasets in Minari and not all offline RL tasks can by tested in this manner (due to complexity of generating an expert policy for a reference maximum score).
This function requires the dataset to have two attributes which can be set when creating the dataset, `ref_min_score` and `ref_max_score`. These attributes are optional and if not present in the dataset `get_normalized_socre()` will through an error.
To set these attributes …
> Get normalized scores

- minari/data_collector/data_collector.py
While creating a dataset I got an error due to a simplification in this previous PR https://github.com/Farama-Foundation/Minari/pull/102 to create non-existing h5py groups. It appears that this code doesn't work as I thought. The following code is an example that we can't check for existing/non-existing groups and create the group as default with the `get` function in h5py:
```python
import h5py
with h5py.File('testing_file.hdf5', 'a') as f:
f.create_group('new_group')
group = f.get('new_group', default=f.create_group('new_group'))
```
The code will throw an error saying that the group already exists.
My proposed fix is a function to implement the previous functionality from the mentioned PR (https://github.com/Farama-Foundation/Minari/pull/102)
> [Bug Fix] Fix h5py group creation

- .github/workflows/build-publish.yml
- .github/workflows/build.yml
- docs/content/dataset_standards.md
- docs/content/minari_cli.md
- minari/__init__.py
- minari/cli.py
- minari/dataset/minari_dataset.py
- minari/dataset/minari_storage.py
- minari/storage/hosting.py
- minari/storage/local.py
- minari/utils.py
- pyproject.toml
- tests/dataset/test_dataset_download.py
- tests/dataset/test_minari_storage.py
- tests/utils/test_dataset_combine.py
This PR adds the `minari_version` attribute to each dataset. This attribute is a version specifier which should contain the Minari versions that the dataset is compatible with (follows [PEP 440](https://peps.python.org/pep-0440/#version-specifiers)). When combining datasets `minari/utils.py::combine_minari_version_specifiers()` will calculate the intersection between all version specifiers for the resulting dataset. If there is no intersection, the datasets don't have any common minari dependency and can't be combined. The version specifier intersection adds a new dependency `portion` to create the version specifier intervals.
`minari_version` is specified when creating a dataset with `create_dataset_from_buffers` or `create_dataset_from_collector_env`. If not given a value, …
> Minari version specifiers

- docs/_scripts/gen_dataset_md.py
Use function `get_remote_dataset_versions()` instead of `find_highest_remote_version()` to generate the dataset doc scripts.
> Fix build docs

- docs/_scripts/gen_dataset_md.py
This PR adds the serialized  attributes `observation_space` and `action_space` to the datasets documentation. We need to add this attributes because these two spaces can be different from the dataset's environment.
> Add dataset spaces to docs

- minari/cli.py
- minari/storage/local.py
- tests/test_cli.py
There was an issue where if you used minari cli it would break if you had datasets that metadata isnt available.  Can see here: 
> Ruggedizes list_local_datasets and adds basic tests for CLI

- docs/tutorials/dataset_creation/point_maze_dataset.py
Fixes #127 
either `action = np.clip(action, env.action_space.low, env.action_space.high, dtype=np.float32)` or `action = np.clip(action, -1, 1, dtype=np.float32)` should fix it
> fix for action with noise type and value needs to be within (low,high)

- minari/storage/local.py
- tests/dataset/test_dataset_download.py
Wanted a small issue/feature to work on and trying to figure out the pre-commit thing as I don't seem able to commit locally because of pyright issues from other files.  Still can't get the pre-commit thing to work.
Allow download=True to be in load_dataset().  Maybe it should be True by default for usability in general but regardless, raise FileNotFound as it did before. 
Fixes #36 
> load dataset with download option

- minari/storage/hosting.py
This PR attempts to fix the slowdown to `list_remote_datasets` introduced in 0.4.0. 
0.4.1 average runtime: 3.2189864999999998
0.3.1 average runtime: average runtime: 0.2429087
patched version: average runtime: 0.7913758999999999
n=20
~~I will also re-run this profiling with n=100 prior to marking this ready for review, since the Google bucket response times seem to add a lot of variance.~~ (I redid n=20 and results seem to replicate well enough I'm convinced this patch is worthwhile)
> attempted to fix list_remote_datasets slowdown

- minari/data_collector/callbacks/step_data.py
- pyproject.toml
Hi, as discussed in https://github.com/Farama-Foundation/Minari/issues/145,  I think we should loose the requirement of typing_extension for compatibility consideration with other packages.  It will cause problem of typing_extension version frequently.
> remove/loose typing_extensions dependency requirement

- minari/utils.py
- tests/utils/test_dataset_combine.py
- tests/utils/test_dataset_creation.py
This is fix for simple bug-fix for function `create_dataset_from_collector_env()`.  
1. Add docstring for parameters
2. Add metadata attribute to dataset, meta data like `algorithm name` `author` `author Email` is not saved though it's passed into function.
for function `create_dataset_from_collector_env()`
ref_min/ref_max score is not saved to metadata, it's easily to find the problem.
I think the bugs are quite clear and definitely is a bug, you can take a look,
> small simple bug-fix: update lost infos in function create_dataset function

- docs/tutorials/dataset_creation/custom_space_serialization.py
This PR adds a new tutorial that goes over serializing custom Gym spaces and shows an example of how to apply a custom observation space to the CartPole environment.
Screenshot of tutorial page:
> Add custom space serialization tutorial

- minari/utils.py
Datasets should have the same observation and action space before being combined. The spaces should also be stored as an attribute in case the dataset has different spaces from the env used to create the dataset (then spaces shouldn't be inferred when loading the dataset)
> Add obs/act spaces when combining datasets

- README.md
- docs/api/data_collector.md
- docs/api/minari_functions.md
- docs/content/basic_usage.md
- docs/tutorials/dataset_creation/custom_space_serialization.py
- docs/tutorials/dataset_creation/observation_space_subseting.py
- docs/tutorials/dataset_creation/point_maze_dataset.py
- docs/tutorials/using_datasets/behavioral_cloning.py
- minari/data_collector/data_collector.py
- minari/utils.py
- tests/common.py
- tests/data_collector/callbacks/test_step_data_callback.py
- tests/data_collector/test_data_collector.py
- tests/dataset/test_minari_storage.py
- tests/utils/test_dataset_combine.py
- tests/utils/test_dataset_creation.py
- Move the function `minari.create_dataset_from_collector_env() to env.create_dataset(). Add deprecation warning for the same.
- Add deprecation warning for making env.save_to_disk private.
Both changes planned for release 0.5.0
N/A
> Deprecate create_dataset_from_collector_env

- README.md
- docs/_scripts/gen_dataset_md.py
- minari/cli.py
- minari/utils.py
The existing `minari list` command contains a "Description" column that is currently unused. This PR removes that column and instead creates a command `minari show <dataset_id>` which provides a detailed description of the dataset. See the screenshots below.
There are other small changes to `minari list`. Notably, the Dataset ID column in `minari list` is now a clickable link to the relevant Farama dataset docs page (once the `docs_url` entries have been populated for each dataset).
The layout for `minari show <dataset_id>` closely follows the dataset docs, so some of the functionality in `docs/_scripts/gen_dataset_md.py` has been moved to `minari/utils.py` so that it can be used for the CLI as well.
- This change requires a …
> Add minari show command

- README.md
- docs/api/data_collector.md
- docs/content/basic_usage.md
- docs/content/dataset_standards.md
- docs/tutorials/dataset_creation/custom_space_serialization.py
- docs/tutorials/dataset_creation/observation_space_subseting.py
- docs/tutorials/dataset_creation/point_maze_dataset.py
- docs/tutorials/using_datasets/behavioral_cloning.py
- minari/__init__.py
- minari/data_collector/__init__.py
- minari/data_collector/callbacks/episode_metadata.py
- minari/data_collector/data_collector.py
- minari/utils.py
- test.py
- tests/common.py
- tests/data_collector/callbacks/test_step_data_callback.py
- tests/data_collector/test_data_collector.py
- tests/dataset/test_minari_dataset.py
- tests/dataset/test_minari_storage.py
- tests/utils/test_dataset_combine.py
- tests/utils/test_dataset_creation.py
- tests/utils/test_get_normalized_score.py
Add deprecation warning to DataCollectorV0 ad we are dropping the versioning following Gymnasium.
> DataCollectorV0 -> DataCollector, deprecation warning

- minari/data_collector/data_collector.py
- minari/dataset/minari_storage.py
- tests/common.py
- tests/data_collector/test_data_collector.py
This PR adds automatic seeding of environments by the DataCollector. If no explicit seed is set, one will be automatically generated when `DataCollector.reset()` is called. The seed is a `uint64`, the maximum integer supported by H5Py.
Reproducibility tests have also been added, both for when an explicit seed is set (addressing issue #15) and when autoseeding.
Other changes:
- Dummy envs are now deterministic
- Minor bugfix: `seed=0` was previously recorded as `seed=None`.
> Add automatic seeding of Datacollector reset

- minari/dataset/minari_dataset.py
- tests/dataset/test_minari_dataset.py
- tests/utils/test_dataset_combine.py
A [recent commit](https://github.com/Farama-Foundation/Minari/commit/dd8406ee8dce27162724fced1f7147d702a70027) modified the type of `MinariDatasetSpec.total_steps` from `int` to `np.int64` (source [here](https://github.com/Farama-Foundation/Minari/blob/e24113bf09b5b1769dafbaf6bb0b2c9b8eb9ffbe/minari/dataset/minari_dataset.py#L54)). This breaks the [TorchRL integration](https://github.com/pytorch/rl/pull/1721) as `np.int64` is not a natively JSON-encodable type. This PR reverts the type back to `int`.
One can confirm that the PR fixes the change with the following script:
```python
from torchrl.data.datasets.minari_data import MinariExperienceReplay
data = MinariExperienceReplay("door-human-v1", batch_size=32)
```
With the current version of Minari built from source, this raises …
> Revert dataset spec total_steps type to int

- docs/content/basic_usage.md
Replace dataset.name with dataset.id in docs.
(The former throws AttributeError: 'MinariDataset' object has no attribute '_name')
- Bug fix 
N/A
> Replace dataset.name with dataset.id

- pyproject.toml
- tests/integrations/test_agile_rl.py
- tests/integrations/test_torch_rl.py
Added smoke tests for AgileRL and TorchRL, two libraries that make use of Minari
> AgileRL and TorchRL smoke tests

- minari/data_collector/data_collector.py
- minari/utils.py
This PR adds an optional description arg to the `create_dataset` and `create_dataset_from_buffers` functions which allow a user to include a brief description of the dataset they are creating. If a description is not provided then a warning will be displayed to the user stating it is recommended to include one.
A minimal working example displaying usage of description:
```python
import gymnasium as gym
from minari.data_collector import DataCollector
env = gym.make("Blackjack-v1")
env = DataCollector(env)
for episode in range(10):
done = False
_, info = env.reset()  # {}
while not done:
action = env.action_space.sample()
_, _, terminated, truncated, _ = env.step(action)
done = terminated or truncated
dataset = env.create_dataset(
dataset_id="blackjack-random-v1", …
```
> Add description arg

- minari/cli.py
- minari/storage/hosting.py
- minari/utils.py
- tests/dataset/test_dataset_download.py
- tests/test_cli.py
When downloading a dataset, one of the flags in the call to `get_remote_dataset_versions` is incorrectly set, and loads a list of the latest versions rather than compatible versions. This prevents users from using older dataset versions even if they are compatible (unless they force-download first). This fixes #200. Tests have been added to check the warning/error logic in `download_dataset()`.
To make the version availability more transparent, the `minari list` CLI has been updated to show a list of compatible versions for each dataset:
This PR also includes some fixes for issues in `minari show` when rendering `">="` and `serialized` spaces.
> Fix download flags and update CLI

- docs/content/dataset_standards.md
- minari/cli.py
- minari/data_collector/data_collector.py
- minari/dataset/minari_storage.py
- minari/utils.py
- pyproject.toml
- tests/common.py
- tests/data_collector/callbacks/test_step_data_callback.py
- tests/data_collector/test_data_collector.py
- tests/dataset/test_minari_storage.py
- tests/utils/test_dataset_creation.py
Make author and email as set in metadata. This allow to correctly have the list of authors when combining multiple datasets
> ENH: Make author and email as set

- docs/_scripts/gen_dataset_md.py
- docs/api/minari_functions.md
- docs/api/namespace/namespace.md
- docs/content/basic_usage.md
- docs/content/dataset_standards.md
- minari/cli.py
- minari/data_collector/data_collector.py
- minari/dataset/minari_dataset.py
- minari/namespace.py
- minari/storage/hosting.py
- minari/storage/local.py
- minari/storage/remotes/cloud_storage.py
- minari/storage/remotes/gcp.py
- minari/utils.py
- tests/common.py
- tests/data_collector/test_data_collector.py
- tests/dataset/test_dataset_download.py
- tests/dataset/test_minari_dataset.py
- tests/dataset/test_minari_storage.py
- tests/test_cli.py
- tests/test_namespace.py
- tests/test_namespace_remote.py
- tests/utils/test_dataset_creation.py
- tests/utils/test_get_normalized_score.py
This PR adds "namespaces", a directory-like hierarchical structure that can be used to group datasets together. For example, creating a dataset with id `my_namespace/cartpole-test-v0` will create a namespace `my_namespace`, containing the CartPole dataset as well with all other datasets starting with "my_namespace/". Namespaces can be arbitrarily nested, and can be assigned metadata which can be used describe the datasets it contains (or any other auxiliary data). These features should help organise the Minari database as it grows, and particularly as third-party datasets are added.
Dataset ids without a "/" are considered to be in the "top-level" namespace, thus this is a non-breaking change.
Internally, namespaces affect three things:
- The first part of the `dataset_id`, e.g. …
> Add namespaces

- docs/_scripts/gen_dataset_md.py
- docs/_scripts/generate_gif.py
- docs/content/dataset_standards.md
- minari/data_collector/data_collector.py
- minari/dataset/minari_dataset.py
- minari/utils.py
- pyproject.toml
- tests/dataset/test_minari_dataset.py
Add requirements in metadata that can be used to indicate which packages and versions are needed for the environment to work as expected.
> ENH: add requirements in metadata

- .github/workflows/docs-test.yml
- .github/workflows/test-integrations.yml
- docs/_scripts/generate_gif.py
- docs/api/minari_dataset/minari_storage.md
- docs/content/dataset_standards.md
- docs/tutorials/using_datasets/IQL_torchrl.py
- docs/tutorials/using_datasets/behavioral_cloning.py
- minari/data_collector/data_collector.py
- minari/data_collector/episode_buffer.py
- minari/dataset/_storages/arrow_storage.py
- minari/dataset/_storages/hdf5_storage.py
- minari/dataset/episode_data.py
- minari/dataset/minari_dataset.py
- minari/dataset/minari_storage.py
- tests/common.py
- tests/data_collector/callbacks/test_step_data_callback.py
- tests/data_collector/test_data_collector.py
- tests/dataset/test_dataset_download.py
- tests/dataset/test_minari_dataset.py
- tests/dataset/test_minari_storage.py
- tests/integrations/test_torch_rl.py
- tests/test_namespace.py
- tests/utils/test_dataset_creation.py
Move the seed attribute in episode_metadata. Thus, seed is not part of `EpisodeData` anymore.
The metadata is a better place for the seed as it is only needed for reproducibility, but not for training. Moreover, for tabular data like Arrow format, this was repeated for any step increasing the size of episode data. 
Finally, for reproducibility purposes, we also want to save reset option argument when present. Again, this will be saved in episode metadata.
> ENH: Move seed to episode metadata

- minari/storage/local.py
Changed how to retrieve `dataset_id` from the path when listing local datasets. Previously, a string returned by `os.path.join` will be appended to the `dataset_ids`. However, this would break on Windows as Windows paths use backslash. Such `dataset_id` doesn't match the required pattern. This fix wraps the path string with `pathlib.PurePath` and converts it to posix path.
Fixes #238.
Before
After
> fix dataset_id error on Windows

- docs/index.md
- minari/cli.py
- minari/storage/hosting.py
- minari/storage/local.py
- minari/storage/remotes/__init__.py
- tests/common.py
- tests/dataset/test_dataset_download.py
Allow CLI commands like
`minari download hf://farama-minari/D4RL/door/human-v2`
`minari list hf://farama-minari/D4RL`
`minari show hf://farama-minari/D4RL/door/human-v2`
Similarly, in `minari.list_remote_datasets` it is now possible to specify `remote_path` and `prefix`. The latter is avaiable also for listing local datasets.
> ENH: Allow complete remote path for list, download and show

- docs/_scripts/gen_dataset_md.py
- minari/data_collector/callbacks/step_callback.py
- minari/data_collector/data_collector.py
- minari/data_collector/episode_buffer.py
- minari/dataset/step_data.py
- tests/common.py
- tests/data_collector/test_data_collector.py
- tests/dataset/test_minari_dataset.py
- tests/dataset/test_minari_storage.py
- tests/utils/test_dataset_creation.py
Use always terminated/truncated when singular (in StepData).
> uniform terminated/truncated naming

- minari/dataset/minari_dataset.py
- minari/storage/local.py
- minari/storage/remotes/huggingface.py
Fix bug where, on Windows, the dataset URL is constructed using a file path generated by os.path.join. This function produces Windows-style paths with backslashes (\), which—when used in a URL—get URL-encoded (e.g., %5C) and result in an "Entry Not Found" error on Hugging Face. Additionally, when parsing the dataset_id from local dataset (local_dsts = local.list_local_datasets() ), the Windows path produces a double slash (\\), leading to an invalid dataset id.
Fixes #277
> Fix incorrect path name on windows
